version: "3.8"
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    env_file:
      - config/development/app.env
    depends_on:
      - db
  prisma-migrate-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: prisma-migrate-dev
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    env_file:
      - config/development/app.env
    depends_on:
      - db
  prisma-studio:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: prisma-studio
    ports:
      - 5555:5555
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    env_file:
      - config/development/app.env
    depends_on:
      - postgres
volumes:
  app_node_modules:
