version: "3.8"
services:
  db:
    image: postgres:14.5-alpine
    container_name: db
    restart: always
    env_file:
      - db.env
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    build:
      context: ../../app
      dockerfile: Dockerfile
      target: production
    container_name: app
    restart: always
    env_file:
      - app.env
    ports:
      - 80:3000
    depends_on:
      - db
  prisma-migrate-deploy:
    build:
      context: ../../app
      dockerfile: Dockerfile
      target: prisma-migrate-deploy
    container_name: prisma-migrate-deploy
    env_file:
      - app.env
    depends_on:
      - db
